version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/web/nginx:/etc/nginx
